### ISSUE TITLE
Divergent history seems to confuse the git count

### ISSUE THREAD

**Issue by stupid-genius** [napalm255/powerbash#16]
This command returns "2", but the git count indicator doesn't reflect that:
<img width="685" alt="image" src="https://github.com/napalm255/powerbash/assets/2687892/5d5b2e6b-0baf-4d0f-b651-7ec25ee9f277">

I have a hunch that it's getting confused by the divergent history (1 ahead, 2 behind):
<img width="46" alt="image" src="https://github.com/napalm255/powerbash/assets/2687892/93821161-43fb-4439-9c78-7f75c952a547">

**Comment by stupid-genius** [comment]
I took a look at the code and it's pretty straightforward and easy to see what it's doing.  It's not obvious why the indicator is wrong.

**Comment by napalm255** [comment]
@stupid-genius Please checkout the PR and see if this fixes things.

**Comment by stupid-genius** [comment]
> @stupid-genius Please checkout the PR and see if this fixes things.

Works like a charm!  Thanks!
